use charper3;
-- 第4题
-- (1)
SELECT DISTINCT SNO FROM SPJ WHERE JNO='J1';
-- (2)
SELECT DISTINCT SNO FROM SPJ WHERE JNO='J1' AND PNO='P1';
-- (3)
SELECT SNO FROM SPJ WHERE JNO='J1' AND PNO IN (SELECT PNO FROM P WHERE COLOR='红');
-- (4)
SELECT DISTINCT JNO FROM J WHERE NOT EXISTS(
    SELECT * FROM SPJ AS SPJ_2 WHERE 
        SPJ_2.SNO IN (SELECT SNO FROM S WHERE S.CITY='天津') 
        AND 
        SPJ_2.PNO IN (SELECT PNO FROM P WHERE COLOR='红')
        AND 
        SPJ_2.JNO= J.JNO
);

-- (5)
SELECT JNO from J AS a WHERE NOT EXISTS(
    SELECT * FROM
        (SELECT b.Pno FROM SPJ AS b WHERE b.Sno='S1') AS d
        WHERE d.Pno NOT IN
        (SELECT c.Pno FROM SPJ AS c WHERE c.Jno=a.Jno)
);

-- 第5题
-- (1)
SELECT SNAME, CITY FROM S;
-- (2)
SELECT PNAME, COLOR, WEIGHT FROM P;
-- (3)
SELECT DISTINCT JNO FROM SPJ WHERE SNO='S1';
-- (4)
SELECT P.PNAME, SPJ.QTY FROM SPJ, P WHERE SPJ.JNO='J2' AND SPJ.PNO=P.PNO;
-- (5)
SELECT DISTINCT PNO FROM SPJ WHERE SNO IN (
    SELECT SNO FROM S WHERE CITY='上海'
);
-- (6)
SELECT DISTINCT JNO FROM SPJ WHERE SPJ.SNO IN (
    SELECT SNO FROM S WHERE CITY='上海'
);
-- (7)
SELECT DISTINCT JNO FROM J WHERE NOT EXISTS (
    SELECT * FROM SPJ WHERE SPJ.SNO IN(
        SELECT SNO FROM S WHERE CITY='天津'
    ) AND SPJ.JNO=J.JNO
);
-- (8)
UPDATE P SET COLOR='蓝' WHERE COLOR='红';
SELECT * FROM P;
-- (9)
UPDATE SPJ SET SNO='S3' WHERE SNO='S5' AND JNO='J4' AND PNO='P6';
SELECT * FROM SPJ;
-- (10)
DELETE FROM SPJ WHERE SNO='S2';
DELETE FROM S WHERE SNO='S2';
SELECT * FROM S;
-- (11)
INSERT INTO S VALUES('S2','盛锡', 10, '北京');
INSERT INTO SPJ VALUES ('S2', 'p4', 'J6', 200);
SELECT * FROM SPJ;

