DATA SEGMENT
    BUF	DB 38H, 73H, 1FH
    MAX	DB ?
DATA ENDS
CODE SEGMENT
	ASSUME	CS:CODE,DS:DATA	
START:	MOV	AX,DATA
	MOV	DS,AX

	MOV	AL,BUF		;将BUF单元送入AL
	CMP	AL,BUF+1	;AL与BUF+1比较	
	JNB	LP1			;如果AL>=BUF+1，就跳转到PL1
	MOV	AL,BUF+1	;如果AL<BUF+1，将BUF+1的内容送入AL	
LP1:CMP	AL,BUF+2	;AL与BUF+2比较
	JAE	LP2			;如果AL>=BUF+2，跳转到PL2
	MOV	AL,BUF+2	;如果AL<BUF+2，将BUF+2送入AL
LP2:MOV	MAX,AL		;将AL送入MAX单元

	MOV	AH,4CH
	INT	21H
CODE ENDS
	END START
