DROP DATABASE IF EXISTS ultraHomework;
CREATE DATABASE ultraHomework;
USE ultraHomework;
DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS (
  BOOK_ISBN INT(13) PRIMARY KEY,
  BOOK_NAME VARCHAR(20) NOT NULL,
  BOOK_AUTHOR_NAME VARCHAR(20) NOT NULL,
  BOOK_INTRO VARCHAR(128),
  BOOK_CLASS VARCHAR(10),
  BOOK_PUB_HOUSE VARCHAR(20),
  BOOK_PUB_TIME INT(8),
  BOOK_PRICE NUMERIC (5,2),
  BOOK_LANGUAGE VARCHAR(20),
  BOOK_NUMBER INT(10),
  BOOK_LACATION VARCHAR(2)
);
DROP TABLE IF EXISTS READER;
CREATE TABLE READER(
  READER_ID INT(11) PRIMARY KEY,
  READER_NAME VARCHAR(20) NOT NULL,
  READER_GENDER VARCHAR(2),
  READER_ADDRESS VARCHAR(128),
  READER_PHONE VARCHAR(11),
  READER_CREDIT INT(3)
);
DROP TABLE IF EXISTS BORROW_AND_RETURN;
CREATE TABLE BORROW_AND_RETURN(
  READER_ID INT (11) NOT NULL,
  BOOK_ISBN INT (13) NOT NULL,
  BORROW_TIME INT (8) NOT NULL,
  RETURN_TIME INT (8) ,
  MAX_TIME INT (8) NOT NULL,
  PRIMARY KEY (READER_ID, BOOK_ISBN),
  FOREIGN KEY (BOOK_ISBN) REFERENCES BOOKS(BOOK_ISBN),
  FOREIGN KEY (READER_ID) REFERENCES READER(READER_ID)
);
DROP TABLE IF EXISTS MANAGERS;
CREATE TABLE MANAGERS (
  ADMIN_ID INT(11) PRIMARY KEY,
  ADMIN_NAME VARCHAR(20) NOT NULL,
  ADMIN_GENDER VARCHAR(2),
  ADMIN_PHONE VARCHAR(11)
);